### ISSUE TITLE
Reporter is hard to get going

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#214]
@mprorock, I'm not able to get your nice reporter running. Following your nice [tutorial](https://github.com/w3c-ccg/traceability-interop/blob/main/reporting/README.md), but get a `Solving environment: failed` because many of the packages aren't found. I think it's an OS issue (I'm on mac), the packages aren't properly/consistently maintained. 
@BenjaminMoe (on ubunto) gets the env built, but it fails at a later step (I forget exactly where and how). 
@mkhraisha made it run last week on windows, so it's not all tragedy. :) 

But it's pretty wonky, and I'm pondering what's the right path forward. I'd be happy to just see the report generated on the server (others may prefer a more hands on experience). Any thoughts on the easiest way ahead?

**Comment by BenjaminMoe** [comment]
@nissimsan fails on mac on the first step `conda env create -f environment.yml`

I'm on ubuntu 22.04, I'm able to run the first command, but the second command `conda activate reporting` fails with:

```
(base) benjamin@M715q:~/Github/traceability-interop/reporting$ conda activate reporting

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/benjamin/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 140, in main
        return activator_main()
      File "/home/benjamin/anaconda3/lib/python3.9/site-packages/conda/activate.py", line 1210, in main
        print(activator.execute(), end='')
      File "/home/benjamin/anaconda3/lib/python3.9/site-packages/conda/activate.py", line 178, in execute
        return getattr(self, self.command)()
      File "/home/benjamin/anaconda3/lib/python3.9/site-packages/conda/activate.py", line 152, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "/home/benjamin/anaconda3/lib/python3.9/site-packages/conda/activate.py", line 300, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "/home/benjamin/anaconda3/lib/python3.9/site-packages/conda/activate.py", line 377, in _build_activate_stack
        self._replace_prefix_in_path(old_conda_prefix, prefix))
      File "/home/benjamin/anaconda3/lib/python3.9/site-packages/conda/activate.py", line 630, in _replace_prefix_in_path
        if path_list[last_idx + 1] == library_bin_dir:
    IndexError: list index out of range

`$ /home/benjamin/anaconda3/bin/conda shell.posix activate reporting`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/benjamin/anaconda3/bin/conda
             CONDA_PREFIX=/home/benjamin/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/benjamin/anaconda3/bin/python
               CONDA_ROOT=/home/benjamin/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/benjamin/anaconda3/bin:/home/benjamin/.nvm/versions/node/v16.14.
                          2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/us
                          r/games:/usr/local/games:/snap/bin:/snap/bin:/home/benjamin/anaconda3/
                          bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/benjamin/anaconda3
            shell level : 1
       user config file : /home/benjamin/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : 3.21.5
         python version : 3.9.7.final.0
       virtual packages : __linux=5.15.0=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/benjamin/anaconda3  (writable)
      conda av data dir : /home/benjamin/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/benjamin/anaconda3/pkgs
                          /home/benjamin/.conda/pkgs
       envs directories : /home/benjamin/anaconda3/envs
                          /home/benjamin/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Linux/5.15.0-27-generic ubuntu/22.04 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```

**Comment by mprorock** [comment]
I'll take a look at this.  I'm on Ubuntu 22.04 and have tested on 20.04. this might be a version issue, or not having dev dependencies.  Will get this replicated, then add a docker file as well to make it easier for folks not used to python dev

**Comment by mprorock** [comment]
> I'd be happy to just see the report generated on the server

Most of the way done with this.  So expect that in the next week or so.

Will have someone on our team update the env file.  I think it is currently pinning certain versions that could cause an issue with mac

**Comment by BenjaminMoe** [comment]
> make it easier for folks not used to python dev

I definitely agree that user error could be an issue here. my experience with python is limited to using it in pre-existing plugin environments where these steps aren't required. But i'm somewhat surprised to see that the simple steps of, execute conda install script, add conda to path, create, activate, run has room for user error.

**Comment by mprorock** [comment]
> Is there a fixed Linux version like Ubuntu 20.04, and a fixed version of Python where the steps described in `reporting/README.md` can be replicated?

Btw, this looks like conda might not be setup right on your system...  Usually if you see this the path is wrong or conda isn't initialized correctly

Some related threads:
https://stackoverflow.com/questions/59510865/unable-to-activate-existing-conda-environments/61255609#61255609

https://stackoverflow.com/questions/66318007/why-am-i-now-getting-a-conda-environment-error-every-time-i-open-new-terminal

**Comment by mprorock** [comment]
> add conda to path, create, activate, run has room for user erro

Quick question on this - did you manually put conda in path, or run `conda init` - the latter is correct, the first can cause issues like this

**Comment by mprorock** [comment]
This is likely the culprit, when I generated that env file I included repo specifications, e.g.
`dbus=1.13.6=h5008d03_3` 
and all other lines should be
`dbus=1.13.6`
and there are a few specific Linux libs in there that we should let dependency resolution handle, like that dbus line I picked out

**Comment by nissimsan** [comment]
I actually tried removing both version and build, which was suggested somewhere on stackoverflow. That caused other things to vomit, and I guess was a step too far - but same direction.

**Comment by mprorock** [comment]
Ah, yeah.  Build is always safe to remove.  Versions on the other hand ...

**Comment by mprorock** [comment]
@nissimsan try pr #215

**Comment by nissimsan** [comment]
Yessss!!!

**Comment by nissimsan** [comment]
@mprorock It works now and it's beautiful! 

Last tiny bit of feedback, running ./reporter.py I got this: 
`OSError: Cannot save file into a non-existent directory: 'data'`
Easily overcome by making a `data` folder. But if you could include a line to make it would be the cherry on top! :) 

Thanks!!!

**Comment by BenjaminMoe** [comment]
>Quick question on this - did you manually put conda in path, or run conda init - the latter is correct, the first can cause issues like this

That's where i probably went wrong. I used [this page](https://www.how2shout.com/linux/how-to-install-anacondaon-ubuntu-22-04-lts-jammy/#3_Add_Environment_variable_for_Anaconda) as a reference. After running the install script, it asked if I wanted to run `conda init`, I replied `yes`. And then I added the path to bashrc, and reloaded the path. 

```
echo "export PATH=$PATH:/home/linuxshout/anaconda3/bin">> ~/.bashrc
source ~/.bashrc
```

**Comment by mprorock** [comment]
> Last tiny bit of feedback, running ./reporter.py I got this: `OSError: Cannot save file into a non-existent directory: 'data'` Easily overcome by making a `data` folder. But if you could include a line to make it would be the cherry on top! :)
> 
> Thanks!!!

done in 61baacb
